### ISSUE TITLE
How do I compile this?

### ISSUE THREAD

**Issue by Prajithp** [ExcelsiorGmbH/MongoDBLogger#1]
Could you please document, how to compile this source code? Also, do you have any pre compiled version of this plugin?

**Comment by Lo5t** [comment]
Hy, the project is combiled with Visual Studio Professional 2012 and the Installer with with Inno Setup Script. I created a tag [release](https://github.com/ExcelsiorGmbH/MongoDBLogger/commit/ee0bd266c79e0f84d9074d26d4ac9820c0503c4d), 
If there are is any further questions don't hesitate to ask.

**Comment by Prajithp** [comment]
@Lo5t Thank you so much for the compiled version :)
